### ISSUE TITLE
Unable to start after first config

### ISSUE THREAD

**Issue by g1sbi** [channel-42/hue-tui#2]
I installed all dependencies, but after running the program I get this:
```
Traceback (most recent call last):
  File "/home/gisbi/.local/bin/huetui", line 666, in <module>
    if int(H.checkup()) == 1:
ValueError: invalid literal for int() with base 10: 'unauthorized user'
```
What can I do? I don't know what logs to post so feel free to tell me which ones are needed.

**Comment by channel-42** [comment]
This happens when the Hue-API-user in `~/.config/hue-tui/login.json` is invalid. Did you create and set an API-user like described [here](https://github.com/channel-42/hue-tui#setup-process)? 

You can either set the IP and API-user manually in `login.json` or delete the config folder with `rm -rf ~/.config/hue-tui` to force the first time setup.

**Comment by g1sbi** [comment]
Fixed, I misinterpreted what the API-user was. I thought it was the ID in discovery.meethue.com but instead I had to go through the whole process. Thanks and sorry!
